import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#181A1B',
    color: '#FFD700',
    padding: 32,
    fontFamily: 'Helvetica',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    borderBottom: '2 solid #FFD700',
    paddingBottom: 10,
  },
  appName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFD700',
    letterSpacing: 1.5,
  },
  section: {
    marginBottom: 24,
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#23272b',
  },
  sectionTitle: {
    color: '#00FFD0',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    letterSpacing: 1,
  },
  value: {
    color: '#fff',
    fontSize: 11,
    marginBottom: 2,
    wordBreak: 'break-word',
  },
  timelineTable: {
    marginTop: 8,
    border: '1 solid #FFD700',
    borderRadius: 6,
    overflow: 'hidden',
  },
  timelineRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottom: '1 solid #FFD700',
    padding: 6,
    backgroundColor: '#181A1B',
  },
  timelineCell: {
    color: '#FFD700',
    fontSize: 13,
    flex: 1,
    textAlign: 'center',
  },
  timelineHeader: {
    backgroundColor: '#23272b',
    color: '#00FFD0',
    fontWeight: 'bold',
    fontSize: 14,
    padding: 6,
    textAlign: 'center',
  },
  footer: {
    marginTop: 32,
    textAlign: 'center',
    color: '#FFD700',
    fontSize: 12,
    borderTop: '1 solid #FFD700',
    paddingTop: 8,
    letterSpacing: 1,
  },
});

function getUserDisplay(user) {
  if (!user) return 'Anonymous';
  if (user.email) return user.email;
  if (user.username) return user.username;
  if (user.name) return user.name;
  return 'User';
}

export default function FaceScanPDF({ timeline, user, model }) {
  const now = new Date();
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.appName}>Multi-Sentiment Analyzer</Text>
        </View>
        <Text style={styles.value}>User: {getUserDisplay(user)}</Text>
        <Text style={styles.value}>{now.toLocaleString()}</Text>
        {model && <Text style={styles.value}>Model: {model}</Text>}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Face Scan Timeline (5s)</Text>
          <View style={styles.timelineTable}>
            <View style={[styles.timelineRow, { backgroundColor: '#23272b' }]}> 
              <Text style={styles.timelineHeader}>Time</Text>
              <Text style={styles.timelineHeader}>Emotion</Text>
              <Text style={styles.timelineHeader}>Confidence</Text>
            </View>
            {timeline && timeline.length > 0 ? (
              timeline.map((entry, i) => (
                <View key={i} style={styles.timelineRow}>
                  <Text style={styles.timelineCell}>{entry.time}</Text>
                  <Text style={styles.timelineCell}>{entry.emotion}</Text>
                  <Text style={styles.timelineCell}>{entry.confidence}%</Text>
                </View>
              ))
            ) : (
              <View style={styles.timelineRow}>
                <Text style={styles.timelineCell} colSpan={3}>No timeline data available.</Text>
              </View>
            )}
          </View>
        </View>
        <Text style={styles.footer}>Generated by Multi-Sentiment Analyzer | {now.getFullYear()}</Text>
      </Page>
    </Document>
  );
} 